const CATEGORY_META={preparation:{label:"準備物"},expense:{label:"経費"},schedule:{label:"スケジュール"},memo:{label:"メモ"}};
const STORAGE_KEY="eventHubLogin";
const state={profile:null,remoteConfig:{appName:"Event Hub",eventId:"",liffId:""},dashboard:null,activeFilter:"preparation",editingType:null,draftMode:"flat",draftRows:[],draftGroups:[],session:null};
document.addEventListener("DOMContentLoaded",async()=>{bindEvents();await boot();});
function bindEvents(){
  document.getElementById("loginButton").addEventListener("click",loginByCode);
  document.getElementById("loginCodeInput").addEventListener("keydown",e=>{if(e.key==="Enter")loginByCode();});
  document.getElementById("logoutButton").addEventListener("click",logout);
  document.getElementById("reloadButton").addEventListener("click",loadDashboard);
  document.getElementById("editCurrentButton").addEventListener("click",()=>openEditor(state.activeFilter));
  document.getElementById("deleteCurrentButton").addEventListener("click",()=>deleteCategory(state.activeFilter));
  document.querySelectorAll(".nav-card").forEach(btn=>btn.addEventListener("click",()=>{state.activeFilter=btn.dataset.type;renderCurrent();}));
  document.querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",closeModal));
  document.getElementById("addRowButton").addEventListener("click",addRow);
  document.getElementById("addGroupButton").addEventListener("click",addGroup);
  document.getElementById("saveCategoryButton").addEventListener("click",saveCurrent);
}
async function boot(){try{state.remoteConfig=await loadRemoteConfig();await initLiffIfPossible();const saved=readSavedLogin();if(saved?.eventId){state.session=saved;showApp();await loadDashboard();}else showLogin();}catch(e){console.error(e);showLogin();setLoginError(e.message);}}
async function loginByCode(){const code=document.getElementById("loginCodeInput").value.trim();if(!code){setLoginError("管理番号またはイベントコードを入力してください。");return;}try{setLoginError("");const res=await fetch(buildGasUrl("loginEvent",{code}));const data=await res.json();if(!data.success)throw new Error(data.message||"ログインできませんでした。");state.session={eventId:data.eventId,eventName:data.eventName,code:data.code};localStorage.setItem(STORAGE_KEY,JSON.stringify(state.session));state.remoteConfig.eventId=data.eventId;showApp();await loadDashboard();}catch(e){console.error(e);setLoginError(e.message);}}
function logout(){localStorage.removeItem(STORAGE_KEY);state.session=null;state.dashboard=null;state.remoteConfig.eventId="";showLogin();}
function showLogin(){document.getElementById("loginView").classList.remove("is-hidden");document.getElementById("appView").classList.add("is-hidden");}
function showApp(){document.getElementById("loginView").classList.add("is-hidden");document.getElementById("appView").classList.remove("is-hidden");setText("currentEventName",state.session?.eventName||"-");}
function readSavedLogin(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");}catch(e){return null;}}
function setLoginError(msg){const el=document.getElementById("loginError");if(el)el.textContent=msg||"";}
async function loadRemoteConfig(){if(!CONFIG.GAS_WEB_APP_URL)throw new Error("config.jsにGAS_WEB_APP_URLが設定されていません。");const res=await fetch(buildGasUrl("getConfig"));const data=await res.json();if(!data.success)throw new Error(data.message||"設定取得に失敗しました。");return data;}
async function initLiffIfPossible(){const id=state.remoteConfig.liffId||"";if(!id||typeof liff==="undefined")return;await liff.init({liffId:id});if(liff.isLoggedIn())state.profile=await liff.getProfile();}
async function loadDashboard(){const eventId=state.session?.eventId||state.remoteConfig.eventId;if(!eventId)throw new Error("イベントが選択されていません。");setStatus("読込中","loading");const res=await fetch(buildGasUrl("getDashboard",{eventId,lineUserId:getLineUserId()}));const data=await res.json();if(!data.success)throw new Error(data.message||"取得に失敗しました。");state.dashboard=data;renderDashboard();setStatus("接続OK","success");}
function buildGasUrl(action,params={}){const url=new URL(CONFIG.GAS_WEB_APP_URL);url.searchParams.set("action",action);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")url.searchParams.set(k,v);});return url.toString();}
async function postGas(action,payload){const body=Object.assign({action,eventId:state.session?.eventId||state.remoteConfig.eventId,lineUserId:getLineUserId(),updatedBy:getDisplayName()},payload);const res=await fetch(CONFIG.GAS_WEB_APP_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)});const data=await res.json();if(!data.success)throw new Error(data.message||"保存に失敗しました。");return data;}
function renderDashboard(){const d=state.dashboard.dashboard||{};setText("eventName",d.eventName||state.session?.eventName||"-");setText("eventDate",formatEventDate(d.eventDate)||"-");setText("venue",d.venue||"-");setText("expectedGuests",d.expectedGuests||"-");setText("lastUpdated","最終更新: "+formatDateTime(d.lastUpdatedAt));setText("currentEventName",d.eventName||state.session?.eventName||"-");setText("preparationCount",countPreparation()+"件");setText("expenseTotal",formatCurrency(sumRows(getRows("expense"))));setText("scheduleCount",getRows("schedule").length+"件");setText("memoCount",getRows("memo").length+"件");renderCurrent();}
function renderCurrent(){const type=state.activeFilter;document.querySelectorAll(".nav-card").forEach(btn=>btn.classList.toggle("is-active",btn.dataset.type===type));setText("panelTitle",CATEGORY_META[type].label);setText("panelDescription","");if(type==="preparation")renderPreparationView();else renderSimpleView(type);}
function renderPreparationView(){const c=document.getElementById("blockList");const data=getPreparationData();if(data.mode==="group"){const groups=data.groups||[];c.innerHTML=`<article class="category-card"><div class="category-card-header"><span class="block-type">準備物</span><span class="block-status">二階層</span></div>${groups.length?groups.map(g=>`<div class="item-group"><h4>${escapeHtml(g.category||"未分類")}</h4>${(g.items||[]).map(renderPrepLine).join("")}</div>`).join(""):'<p class="empty-state">準備物がありません。</p>'}</article>`;}else{const rows=data.items||[];c.innerHTML=`<article class="category-card"><div class="category-card-header"><span class="block-type">準備物</span><span class="block-status">一階層</span></div><div class="item-list">${rows.length?rows.map(renderPrepRow).join(""):'<p class="empty-state">準備物がありません。</p>'}</div></article>`;}}
function renderPrepRow(r){return `<div class="item-row"><strong>${escapeHtml(r.name||"")}</strong><span>${escapeHtml(r.qty||"")}</span><small>${escapeHtml(r.memo||"")}</small></div>`;}
function renderPrepLine(r){return `<div class="item-line"><strong>・${escapeHtml(r.name||"")}</strong><span>${escapeHtml(r.qty||"")}</span><small>${escapeHtml(r.memo||"")}</small></div>`;}
function renderSimpleView(type){const rows=getRows(type);const total=type==="expense"?`<small class="amount">合計 ${formatCurrency(sumRows(rows))}</small>`:"";document.getElementById("blockList").innerHTML=`<article class="category-card"><div class="category-card-header"><span class="block-type">${CATEGORY_META[type].label}</span><span class="block-status">一括管理</span></div><div class="item-list">${rows.length?rows.map(r=>renderSimpleRow(r,type)).join(""):'<p class="empty-state">項目がありません。</p>'}</div>${total}</article>`;}
function renderSimpleRow(r,type){if(type==="expense")return `<div class="item-row"><strong>${escapeHtml(r.item||r.title||"")}</strong><span>${formatCurrency(r.amount||0)}</span><small>${escapeHtml(r.memo||"")}</small></div>`;if(type==="schedule")return `<div class="item-row"><strong>${escapeHtml(r.time||"")}</strong><span>${escapeHtml(r.item||r.title||"")}</span><small>${escapeHtml(r.memo||"")}</small></div>`;return `<div class="item-row"><strong>${escapeHtml(r.item||r.title||"")}</strong><span></span><small>${escapeHtml(r.memo||"")}</small></div>`;}
function openEditor(type){state.editingType=type;setText("modalTitle",CATEGORY_META[type].label+"編集");setText("saveCategoryButton",CATEGORY_META[type].label+"を更新");if(type==="preparation"){const data=getPreparationData();state.draftMode=data.mode||"flat";state.draftRows=(data.items||[]).map(x=>Object.assign({},x));state.draftGroups=(data.groups||[]).map(g=>({category:g.category||"",items:(g.items||[]).map(x=>Object.assign({},x))}));}else{state.draftMode="flat";state.draftRows=getRows(type).map(x=>Object.assign({},x));}if(!state.draftRows.length&&type!=="preparation")state.draftRows=[emptySimpleRow(type)];if(type==="preparation"&&state.draftMode==="flat"&&!state.draftRows.length)state.draftRows=[emptyPrepRow()];if(type==="preparation"&&state.draftMode==="group"&&!state.draftGroups.length)state.draftGroups=[{category:"",items:[emptyPrepRow()]}];renderModeSwitch();renderEditorRows();openModal();}
function renderModeSwitch(){const a=document.getElementById("modeSwitch");if(state.editingType!=="preparation"){a.innerHTML="";document.getElementById("addGroupButton").style.display="none";return;}a.innerHTML=`<span>準備物の構造</span><button class="mode-button ${state.draftMode==="flat"?"is-active":""}" id="flatModeButton">一階層</button><button class="mode-button ${state.draftMode==="group"?"is-active":""}" id="groupModeButton">二階層</button>`;document.getElementById("flatModeButton").addEventListener("click",()=>{state.draftMode="flat";if(!state.draftRows.length)state.draftRows=flattenGroups();renderModeSwitch();renderEditorRows();});document.getElementById("groupModeButton").addEventListener("click",()=>{state.draftMode="group";if(!state.draftGroups.length)state.draftGroups=[{category:"",items:state.draftRows.length?state.draftRows:[emptyPrepRow()]}];renderModeSwitch();renderEditorRows();});}
function renderEditorRows(){const type=state.editingType,w=document.getElementById("batchRows");document.getElementById("addGroupButton").style.display=(type==="preparation"&&state.draftMode==="group")?"inline-flex":"none";document.getElementById("addRowButton").style.display=(type==="preparation"&&state.draftMode==="group")?"none":"inline-flex";if(type==="preparation"&&state.draftMode==="group"){w.innerHTML=state.draftGroups.map((g,gi)=>`<div class="group-editor"><div class="group-header"><input data-group="${gi}" data-field="category" placeholder="例：景品" value="${escapeAttr(g.category||"")}"><button class="danger-button" data-delete-group="${gi}" type="button">カテゴリ削除</button></div><div class="group-items">${(g.items||[]).map((r,ri)=>prepItemEditor(r,gi,ri)).join("")}</div><button class="secondary-button" data-add-item="${gi}" type="button">項目追加</button></div>`).join("");}else{w.innerHTML=state.draftRows.map((r,i)=>rowEditor(r,i,type)).join("");}bindEditorInputs();updateDraftTotal();}
function prepItemEditor(r,gi,ri){return `<div class="group-item"><input data-group="${gi}" data-row="${ri}" data-field="name" placeholder="項目" value="${escapeAttr(r.name||"")}"><select data-group="${gi}" data-row="${ri}" data-field="qty">${qtyOptions(r.qty)}</select><textarea data-group="${gi}" data-row="${ri}" data-field="memo" placeholder="メモ">${escapeHtml(r.memo||"")}</textarea><button class="danger-button" data-delete-item="${gi}:${ri}" type="button">削除</button></div>`;}
function rowEditor(r,i,type){if(type==="preparation")return `<div class="batch-row"><input data-index="${i}" data-field="name" placeholder="項目" value="${escapeAttr(r.name||"")}"><select data-index="${i}" data-field="qty">${qtyOptions(r.qty)}</select><textarea data-index="${i}" data-field="memo" placeholder="メモ">${escapeHtml(r.memo||"")}</textarea><button class="danger-button" data-delete-row="${i}" type="button">削除</button></div>`;if(type==="expense")return `<div class="batch-row"><input data-index="${i}" data-field="item" placeholder="項目" value="${escapeAttr(r.item||r.title||"")}"><input data-index="${i}" data-field="amount" type="number" placeholder="金額" value="${escapeAttr(r.amount||"")}"><textarea data-index="${i}" data-field="memo" placeholder="備考">${escapeHtml(r.memo||"")}</textarea><button class="danger-button" data-delete-row="${i}" type="button">削除</button></div>`;if(type==="schedule")return `<div class="batch-row"><input data-index="${i}" data-field="time" placeholder="時間" value="${escapeAttr(r.time||"")}"><input data-index="${i}" data-field="item" placeholder="項目" value="${escapeAttr(r.item||r.title||"")}"><textarea data-index="${i}" data-field="memo" placeholder="備考">${escapeHtml(r.memo||"")}</textarea><button class="danger-button" data-delete-row="${i}" type="button">削除</button></div>`;return `<div class="batch-row"><input data-index="${i}" data-field="item" placeholder="項目" value="${escapeAttr(r.item||r.title||"")}"><span></span><textarea data-index="${i}" data-field="memo" placeholder="備考">${escapeHtml(r.memo||"")}</textarea><button class="danger-button" data-delete-row="${i}" type="button">削除</button></div>`;}
function bindEditorInputs(){document.querySelectorAll("#batchRows input,#batchRows textarea,#batchRows select").forEach(el=>el.addEventListener("input",updateDraftFromInput));document.querySelectorAll("[data-delete-row]").forEach(b=>b.addEventListener("click",e=>{state.draftRows.splice(Number(e.target.dataset.deleteRow),1);if(!state.draftRows.length)state.draftRows=[emptySimpleRow(state.editingType)];renderEditorRows();}));document.querySelectorAll("[data-delete-group]").forEach(b=>b.addEventListener("click",e=>{state.draftGroups.splice(Number(e.target.dataset.deleteGroup),1);if(!state.draftGroups.length)state.draftGroups=[{category:"",items:[emptyPrepRow()]}];renderEditorRows();}));document.querySelectorAll("[data-add-item]").forEach(b=>b.addEventListener("click",e=>{state.draftGroups[Number(e.target.dataset.addItem)].items.push(emptyPrepRow());renderEditorRows();}));document.querySelectorAll("[data-delete-item]").forEach(b=>b.addEventListener("click",e=>{const [gi,ri]=e.target.dataset.deleteItem.split(":").map(Number);state.draftGroups[gi].items.splice(ri,1);if(!state.draftGroups[gi].items.length)state.draftGroups[gi].items=[emptyPrepRow()];renderEditorRows();}));}
function updateDraftFromInput(e){const el=e.target,f=el.dataset.field,v=el.value;if(el.dataset.group!==undefined&&el.dataset.row!==undefined){state.draftGroups[Number(el.dataset.group)].items[Number(el.dataset.row)][f]=v;}else if(el.dataset.group!==undefined){state.draftGroups[Number(el.dataset.group)][f]=v;}else state.draftRows[Number(el.dataset.index)][f]=v;updateDraftTotal();}
function addRow(){state.draftRows.push(emptySimpleRow(state.editingType));renderEditorRows();}
function addGroup(){state.draftGroups.push({category:"",items:[emptyPrepRow()]});renderEditorRows();}
function qtyOptions(s){let h="";for(let i=1;i<=20;i++)h+=`<option value="${i}" ${String(s)==String(i)?"selected":""}>${i}</option>`;h+=`<option value="other" ${String(s)==="other"?"selected":""}>その他</option>`;return h;}
async function saveCurrent(){const type=state.editingType;let content,amount=0;if(type==="preparation"){content=JSON.stringify(state.draftMode==="group"?{mode:"group",groups:cleanGroups()}:{mode:"flat",items:cleanPrepRows(state.draftRows)});}else{const rows=cleanSimpleRows(state.draftRows,type);content=JSON.stringify(rows);if(type==="expense")amount=sumRows(rows);}try{setStatus(CATEGORY_META[type].label+"保存中","loading");const block=getBlock(type);const p={blockType:type,blockTitle:CATEGORY_META[type].label,blockContent:content,amount,status:"更新済み",sortOrder:getSortOrder(type)};if(block?.blockId)await postGas("updateBlock",Object.assign({blockId:block.blockId},p));else await postGas("createBlock",p);closeModal();await loadDashboard();}catch(e){alert(e.message);setStatus("保存エラー","error");}}
async function deleteCategory(type){const block=getBlock(type);if(!block?.blockId){alert("削除できるデータがありません。");return;}if(!confirm(CATEGORY_META[type].label+"全体を削除しますか？"))return;await postGas("deleteBlock",{blockId:block.blockId});await loadDashboard();}
function getBlock(type){return(state.dashboard?.blocks||[]).find(b=>b.blockType===type)||null;}
function getRows(type){const block=getBlock(type);if(!block)return[];try{const x=JSON.parse(block.blockContent||"[]");return Array.isArray(x)?x:[]}catch(e){return block.blockContent?block.blockContent.split(/\n+/).filter(Boolean).map(t=>({item:t,memo:""})):[]}}
function getPreparationData(){const block=getBlock("preparation");if(!block)return{mode:"flat",items:[]};try{const x=JSON.parse(block.blockContent||"{}");if(Array.isArray(x))return{mode:"flat",items:x.map(v=>({name:v.name||v.item||v.title||"",qty:v.qty||"",memo:v.memo||""}))};if(x.mode)return x;}catch(e){}return{mode:"flat",items:block.blockContent?block.blockContent.split(/\n+/).filter(Boolean).map(t=>({name:t,qty:"",memo:""})):[]};}
function countPreparation(){const d=getPreparationData();return d.mode==="group"?(d.groups||[]).reduce((s,g)=>s+(g.items||[]).length,0):(d.items||[]).length;}
function cleanPrepRows(rows){return rows.filter(r=>(r.name||"").trim()||(r.memo||"").trim()).map(r=>({name:(r.name||"").trim(),qty:r.qty||"",memo:(r.memo||"").trim()}));}
function cleanGroups(){return state.draftGroups.map(g=>({category:(g.category||"").trim(),items:cleanPrepRows(g.items||[])})).filter(g=>g.category||g.items.length);}
function cleanSimpleRows(rows,type){return rows.filter(r=>(r.item||r.title||r.time||"").trim()||(r.memo||"").trim()||Number(r.amount||0)>0).map(r=>({time:r.time||"",item:(r.item||r.title||"").trim(),amount:Number(r.amount||0),memo:(r.memo||"").trim()}));}
function emptyPrepRow(){return{name:"",qty:"1",memo:""};}function emptySimpleRow(type){if(type==="expense")return{item:"",amount:"",memo:""};if(type==="schedule")return{time:"",item:"",memo:""};return type==="preparation"?emptyPrepRow():{item:"",memo:""};}
function flattenGroups(){return state.draftGroups.flatMap(g=>(g.items||[]));}function sumRows(rows){return rows.reduce((s,r)=>s+Number(r.amount||0),0);}function getSortOrder(type){return{preparation:1,expense:2,schedule:3,memo:4}[type]||999;}function openModal(){document.getElementById("batchModal").classList.add("is-open");}function closeModal(){document.getElementById("batchModal").classList.remove("is-open");state.editingType=null;}function getLineUserId(){return state.profile?.userId||"";}function getDisplayName(){return state.profile?.displayName||"unknown";}function setStatus(t,type){const e=document.getElementById("connectionStatus");if(!e)return;e.textContent=t;e.className=`status-badge ${type||""}`;}function setText(id,t){const e=document.getElementById(id);if(e)e.textContent=t;}function formatCurrency(v){return new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(Number(v||0));}function formatEventDate(v){if(!v)return"";const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);}function formatDateTime(v){if(!v)return"-";const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(d);}function escapeHtml(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}function escapeAttr(v){return escapeHtml(v).replace(/`/g,"&#096;");}
