const state={liffReady:false,profile:null,remoteConfig:{appName:"Event Hub",eventId:"OFFMEETING_001",liffId:""},dashboard:null,activeFilter:null};
document.addEventListener("DOMContentLoaded",async()=>{bindEvents();await boot();});
function bindEvents(){const r=document.getElementById("reloadButton");if(r)r.addEventListener("click",async()=>{await loadDashboard();});document.querySelectorAll(".nav-card").forEach(b=>{b.addEventListener("click",()=>{const t=b.dataset.type;state.activeFilter=state.activeFilter===t?null:t;renderCurrentBlocks();});});}
async function boot(){setStatus("起動中","loading");try{state.remoteConfig=await loadRemoteConfig();await initLiffIfPossible();await loadDashboard();setStatus("接続OK","success");}catch(e){console.error(e);setStatus("接続エラー","error");renderError(e.message||"初期化に失敗しました。");}}
async function loadRemoteConfig(){if(!CONFIG.GAS_WEB_APP_URL){throw new Error("config.jsにGAS_WEB_APP_URLが設定されていません。");}const u=buildGasUrl("getConfig");const r=await fetch(u);const d=await r.json();if(!d.success)throw new Error(d.message||"設定取得に失敗しました。");return d;}
async function initLiffIfPossible(){const id=state.remoteConfig?.liffId||"";if(!id||typeof liff==="undefined"){console.log("LIFF initialization skipped.");return;}await liff.init({liffId:id});state.liffReady=true;if(liff.isLoggedIn())state.profile=await liff.getProfile();}
async function loadDashboard(){setStatus("読込中","loading");const u=buildGasUrl("getDashboard",{eventId:state.remoteConfig.eventId||"OFFMEETING_001",lineUserId:state.profile?.userId||""});const r=await fetch(u);const d=await r.json();if(!d.success)throw new Error(d.message||"ダッシュボード取得に失敗しました。");state.dashboard=d;state.activeFilter=null;renderDashboard(d);setStatus("接続OK","success");}
function buildGasUrl(action,params={}){const u=new URL(CONFIG.GAS_WEB_APP_URL);u.searchParams.set("action",action);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,v);});return u.toString();}
function renderDashboard(d){const b=d.dashboard||{},s=d.summary||{};setText("eventName",b.eventName||"-");setText("eventDate",b.eventDate||"-");setText("venue",b.venue||"-");setText("expectedGuests",b.expectedGuests||"-");setText("lastUpdated","最終更新: "+formatDateTime(b.lastUpdatedAt));setText("preparationCount",`${s.preparationCount||0}件`);setText("expenseTotal",formatCurrency(s.expenseTotal||0));setText("scheduleCount",`${s.scheduleCount||0}件`);setText("memoCount",`${s.memoCount||0}件`);renderCurrentBlocks();}
function renderCurrentBlocks(){if(!state.dashboard)return;const bs=state.dashboard.blocks||[];const fs=state.activeFilter?bs.filter(b=>b.blockType===state.activeFilter):bs;const m={preparation:"準備物",expense:"経費",schedule:"スケジュール",memo:"メモ"};setText("panelTitle",state.activeFilter?`${m[state.activeFilter]||"カテゴリ"}一覧`:"ダッシュボード概要");setText("panelDescription",state.activeFilter?"選択したカテゴリのみ表示しています。もう一度押すと全体表示に戻ります。":"各カテゴリの概要を表示しています。");renderBlocks(fs);}
function renderBlocks(bs){const c=document.getElementById("blockList");if(!c)return;if(!bs.length){c.innerHTML='<p class="empty-state">表示できるブロックがありません。</p>';return;}c.innerHTML=bs.map(b=>`<article class="block-card"><div class="block-card-header"><span class="block-type">${labelBlockType(b.blockType)}</span><span class="block-status">${escapeHtml(b.status||"未設定")}</span></div><h3>${escapeHtml(b.blockTitle||"無題")}</h3><p>${escapeHtml(b.blockContent||"").replace(/\n/g,"<br>")}</p>${Number(b.amount||0)>0?`<small class="amount">${formatCurrency(b.amount)}</small>`:""}</article>`).join("");}
function renderError(m){const c=document.getElementById("blockList");if(c)c.innerHTML=`<p class="error-state">${escapeHtml(m)}</p>`;}
function setStatus(t,type){const e=document.getElementById("connectionStatus");if(!e)return;e.textContent=t;e.className=`status-badge ${type||""}`;}
function setText(id,t){const e=document.getElementById(id);if(e)e.textContent=t;}
function labelBlockType(t){return{preparation:"準備物",expense:"経費",schedule:"スケジュール",memo:"メモ",task:"タスク",link:"リンク",other:"その他"}[t]||"その他";}
function formatCurrency(v){return new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(Number(v||0));}
function formatDateTime(v){if(!v)return"-";const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(d);}
function escapeHtml(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
