const state={liffReady:false,profile:null,remoteConfig:{appName:"Event Hub",eventId:"OFFMEETING_001",liffId:""},dashboard:null,activeFilter:null,currentBlock:null,expenseDraft:[]};
document.addEventListener("DOMContentLoaded",async()=>{ensureModalRoot();bindEvents();await boot();});
function bindEvents(){const r=document.getElementById("reloadButton");if(r)r.addEventListener("click",async()=>{await loadDashboard();});const c=document.getElementById("createButton");if(c)c.addEventListener("click",()=>state.activeFilter==="expense"?openExpenseEditor():openGenericEditor(null));document.querySelectorAll(".nav-card").forEach(b=>{b.addEventListener("click",()=>{const t=b.dataset.type;state.activeFilter=state.activeFilter===t?null:t;renderCurrentBlocks();});});}
async function boot(){setStatus("起動中","loading");try{state.remoteConfig=await loadRemoteConfig();await initLiffIfPossible();await loadDashboard();setStatus("接続OK","success");}catch(e){console.error(e);setStatus("接続エラー","error");renderError(e.message||"初期化に失敗しました。");}}
async function loadRemoteConfig(){if(!CONFIG.GAS_WEB_APP_URL)throw new Error("config.jsにGAS_WEB_APP_URLが設定されていません。");const r=await fetch(buildGasUrl("getConfig"));const d=await r.json();if(!d.success)throw new Error(d.message||"設定取得に失敗しました。");return d;}
async function initLiffIfPossible(){const id=state.remoteConfig?.liffId||"";if(!id||typeof liff==="undefined")return;await liff.init({liffId:id});state.liffReady=true;if(liff.isLoggedIn())state.profile=await liff.getProfile();}
async function loadDashboard(){setStatus("読込中","loading");const r=await fetch(buildGasUrl("getDashboard",{eventId:state.remoteConfig.eventId||"OFFMEETING_001",lineUserId:getLineUserId()}));const d=await r.json();if(!d.success)throw new Error(d.message||"ダッシュボード取得に失敗しました。");state.dashboard=d;renderDashboard(d);setStatus("接続OK","success");}
function buildGasUrl(action,params={}){const u=new URL(CONFIG.GAS_WEB_APP_URL);u.searchParams.set("action",action);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,v);});return u.toString();}
async function postGas(action,payload={}){const body=Object.assign({action,eventId:state.remoteConfig.eventId||"OFFMEETING_001",lineUserId:getLineUserId(),updatedBy:getDisplayName()},payload);const r=await fetch(CONFIG.GAS_WEB_APP_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body)});const d=await r.json();if(!d.success)throw new Error(d.message||"保存に失敗しました。");return d;}
function renderDashboard(d){const b=d.dashboard||{},s=d.summary||{};setText("eventName",b.eventName||"-");setText("eventDate",b.eventDate||"-");setText("venue",b.venue||"-");setText("expectedGuests",b.expectedGuests||"-");setText("lastUpdated","最終更新: "+formatDateTime(b.lastUpdatedAt));setText("preparationCount",`${s.preparationCount||0}件`);setText("expenseTotal",formatCurrency(getExpenseTotal()));setText("scheduleCount",`${s.scheduleCount||0}件`);setText("memoCount",`${s.memoCount||0}件`);renderCurrentBlocks();}
function renderCurrentBlocks(){if(!state.dashboard)return;const bs=state.dashboard.blocks||[];const m={preparation:"準備物",expense:"経費",schedule:"スケジュール",memo:"メモ"};setText("panelTitle",state.activeFilter?`${m[state.activeFilter]||"カテゴリ"}一覧`:"ダッシュボード概要");setText("panelDescription",state.activeFilter?"選択したカテゴリのみ表示しています。":"各カテゴリの概要を表示しています。");if(state.activeFilter==="expense"){renderExpenseBlock();return;}const fs=state.activeFilter?bs.filter(b=>b.blockType===state.activeFilter):bs;renderBlocks(fs);}
function renderBlocks(bs){const c=document.getElementById("blockList");if(!c)return;if(!bs.length){c.innerHTML='<p class="empty-state">表示できるブロックがありません。</p>';return;}c.innerHTML=bs.map(b=>`<article class="block-card" data-block-id="${escapeHtml(b.blockId||"")}"><div class="block-card-header"><span class="block-type">${labelBlockType(b.blockType)}</span><span class="block-status">${escapeHtml(b.status||"未設定")}</span></div><h3>${escapeHtml(b.blockTitle||"無題")}</h3><p>${escapeHtml(b.blockContent||"").replace(/\n/g,"<br>")}</p>${Number(b.amount||0)>0?`<small class="amount">${formatCurrency(b.amount)}</small>`:""}</article>`).join("");c.querySelectorAll(".block-card").forEach(card=>card.addEventListener("click",()=>openGenericEditor((state.dashboard.blocks||[]).find(x=>x.blockId===card.dataset.blockId))));}
function getExpenseBlock(){return(state.dashboard?.blocks||[]).find(b=>b.blockType==="expense")||null;}
function parseExpenseRows(block){if(!block)return[];try{const rows=JSON.parse(block.blockContent||"[]");return Array.isArray(rows)?rows:[];}catch(e){return block.blockContent?[{title:block.blockTitle||"経費",amount:Number(block.amount||0),memo:block.blockContent}]:[];}}
function getExpenseTotal(){return parseExpenseRows(getExpenseBlock()).reduce((s,r)=>s+Number(r.amount||0),0);}
function renderExpenseBlock(){const c=document.getElementById("blockList");const block=getExpenseBlock();const rows=parseExpenseRows(block);const total=rows.reduce((s,r)=>s+Number(r.amount||0),0);if(!c)return;c.innerHTML=`<article class="block-card"><div class="block-card-header"><span class="block-type">経費</span><span class="block-status">${escapeHtml(block?.status||"一括管理")}</span></div><h3>経費ブロック</h3><p>この経費は全体をまとめて編集し、「経費を更新」を押した時だけ保存されます。</p><div class="expense-table">${rows.length?rows.map(r=>`<div class="expense-view-row"><strong>${escapeHtml(r.title||"")}</strong><span>${formatCurrency(r.amount||0)}</span><small>${escapeHtml(r.memo||"")}</small></div>`).join(""):'<p class="empty-state">経費項目がありません。</p>'}</div><small class="amount">合計 ${formatCurrency(total)}</small><div class="panel-actions" style="margin-top:14px"><button class="primary-button" id="editExpenseButton">経費を編集</button><button class="danger-button" id="deleteExpenseButton">経費全体を削除</button></div></article>`;document.getElementById("editExpenseButton").addEventListener("click",openExpenseEditor);document.getElementById("deleteExpenseButton").addEventListener("click",deleteExpenseBlock);}
function openExpenseEditor(){const block=getExpenseBlock();state.currentBlock=block;state.expenseDraft=parseExpenseRows(block);if(!state.expenseDraft.length)state.expenseDraft=[{title:"",amount:"",memo:""}];renderExpenseEditor();openModal();}
function renderExpenseEditor(){const c=document.getElementById("modalContent");c.innerHTML=`<div class="modal-header"><h2>経費ブロック編集</h2><button class="icon-button" type="button" id="closeModalButton">×</button></div><p class="modal-note">行を追加・削除・編集しても、下の「経費を更新」を押すまで保存されません。</p><div id="expenseRows"></div><div class="panel-actions"><button class="secondary-button" id="addExpenseRow">行を追加</button><strong id="expenseDraftTotal"></strong></div><div class="modal-actions"><button class="secondary-button" id="cancelExpense">キャンセル</button><button class="primary-button" id="saveExpense">経費を更新</button></div>`;document.getElementById("closeModalButton").addEventListener("click",closeModal);document.getElementById("cancelExpense").addEventListener("click",closeModal);document.getElementById("addExpenseRow").addEventListener("click",()=>{state.expenseDraft.push({title:"",amount:"",memo:""});renderExpenseRows();});document.getElementById("saveExpense").addEventListener("click",saveExpenseBlock);renderExpenseRows();}
function renderExpenseRows(){const wrap=document.getElementById("expenseRows");if(!wrap)return;wrap.innerHTML=state.expenseDraft.map((r,i)=>`<div class="expense-edit-row"><input data-expense-field="title" data-index="${i}" placeholder="項目名" value="${escapeAttr(r.title||"")}"><input data-expense-field="amount" data-index="${i}" type="number" min="0" step="1" placeholder="金額" value="${escapeAttr(r.amount||"")}"><input data-expense-field="memo" data-index="${i}" placeholder="メモ" value="${escapeAttr(r.memo||"")}"><button class="danger-button" type="button" data-delete-expense="${i}">削除</button></div>`).join("");wrap.querySelectorAll("input").forEach(input=>input.addEventListener("input",e=>{const i=Number(e.target.dataset.index);const f=e.target.dataset.expenseField;state.expenseDraft[i][f]=e.target.value;updateExpenseDraftTotal();}));wrap.querySelectorAll("[data-delete-expense]").forEach(btn=>btn.addEventListener("click",e=>{state.expenseDraft.splice(Number(e.target.dataset.deleteExpense),1);renderExpenseRows();}));updateExpenseDraftTotal();}
function updateExpenseDraftTotal(){const t=state.expenseDraft.reduce((s,r)=>s+Number(r.amount||0),0);setText("expenseDraftTotal","合計 "+formatCurrency(t));}
async function saveExpenseBlock(){const rows=state.expenseDraft.filter(r=>(r.title||"").trim()||Number(r.amount||0)>0||(r.memo||"").trim());const total=rows.reduce((s,r)=>s+Number(r.amount||0),0);setStatus("経費保存中","loading");try{if(state.currentBlock?.blockId){await postGas("updateBlock",{blockId:state.currentBlock.blockId,blockType:"expense",blockTitle:"経費",blockContent:JSON.stringify(rows),amount:total,status:"更新済み"});}else{await postGas("createBlock",{blockType:"expense",blockTitle:"経費",blockContent:JSON.stringify(rows),amount:total,status:"更新済み",sortOrder:2});}closeModal();await loadDashboard();}catch(e){alert(e.message);setStatus("保存エラー","error");}}
async function deleteExpenseBlock(){const block=getExpenseBlock();if(!block?.blockId){alert("削除できる経費ブロックがありません。");return;}if(!confirm("経費ブロック全体を削除しますか？"))return;setStatus("削除中","loading");try{await postGas("deleteBlock",{blockId:block.blockId});await loadDashboard();}catch(e){alert(e.message);setStatus("削除エラー","error");}}
function openGenericEditor(block){alert("このカテゴリの編集UIは次の実装対象です。現在は経費ブロック編集を優先しています。");}
function ensureModalRoot(){if(document.getElementById("dynamicModal"))return;const div=document.createElement("div");div.id="dynamicModal";div.className="modal";div.innerHTML='<div class="modal-backdrop" id="dynamicModalBackdrop"></div><section class="modal-panel"><div id="modalContent"></div></section>';document.body.appendChild(div);document.getElementById("dynamicModalBackdrop").addEventListener("click",closeModal);}
function openModal(){document.getElementById("dynamicModal").classList.add("is-open");}
function closeModal(){document.getElementById("dynamicModal").classList.remove("is-open");state.expenseDraft=[];}
function renderError(m){const c=document.getElementById("blockList");if(c)c.innerHTML=`<p class="error-state">${escapeHtml(m)}</p>`;}
function getLineUserId(){return state.profile?.userId||"";}function getDisplayName(){return state.profile?.displayName||"unknown";}function setStatus(t,type){const e=document.getElementById("connectionStatus");if(!e)return;e.textContent=t;e.className=`status-badge ${type||""}`;}function setText(id,t){const e=document.getElementById(id);if(e)e.textContent=t;}function labelBlockType(t){return{preparation:"準備物",expense:"経費",schedule:"スケジュール",memo:"メモ",task:"タスク",link:"リンク",other:"その他"}[t]||"その他";}function formatCurrency(v){return new Intl.NumberFormat("ja-JP",{style:"currency",currency:"JPY",maximumFractionDigits:0}).format(Number(v||0));}function formatDateTime(v){if(!v)return"-";const d=new Date(v);if(Number.isNaN(d.getTime()))return v;return new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(d);}function escapeHtml(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}function escapeAttr(v){return escapeHtml(v).replace(/`/g,"&#096;");}
